add yubico to /etc/pam.d
QubesOS/qubes-app-yubikey pull request #3
Opened 2017-11-14 15:10 UTC by adrelanos

Reason: copying from Qubes documentation to dom0 is impossible for most users. Sure, it's possible to look up the Qubes documentation on doing that, but it's intentionally hard. At the same time, it's hard and error prone to type the following by hand. (Forget 10 finger typing. Imagine many users who do two finger search system typing. :)

> `auth [success=done default=ignore] pam_exec.so expose_authtok quiet /usr/bin/yk-auth AESKEY PASSWORD-HASH`

Once /etc/pam.d/yubico is on the system, users can either copy and paste from there or add `auth include yubico` (a lot less and simpler to type) to /etc/pam.d/xscreensaver. (Untested.) (The [blog post](https://mig5.net/content/yubikey-challenge-response-mode-qubes) by @mig5 implies this is possible.) (Or at some point in future, from there we could even use alt to simplify this further using salt.)

2017-11-14 22:37 UTC, marmarek requested changes
I'd also consider renaming this file to yubikey to point specific product, not company name...

2017-11-14 22:37 UTC, marmarek commented on etc/pam.d/yubico
> +auth [success=done default=ignore] pam_exec.so expose_authtok quiet /usr/bin/yk-auth AESKEY PASSWORD-HASH
The version of the script in this repo get the key/password-hash from config file, not from arguments. So arguments are useless here.

2017-11-15 01:26 UTC, adrelanos commented
Right. This has both been addressed.

2017-11-19 15:01 UTC, marmarek approved these changes

2017-11-19 15:12 UTC, merged